version: "3.8"

services:
  keycloak:
    # E-Mail verification action is only available in nightly until 26.2 is released
    image: quay.io/keycloak/keycloak:nightly # 26.2 nightly
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_FEATURES: "passkeys,update-email"
      DEBUG: "true"
    command: "start --http-enabled true --hostname-strict false"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./create-clients.sh:/create-clients.sh:Z
    network_mode: host
volumes:
  kc_data: